version: '3.8'

services:
  securechain-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    restart: unless-stopped
    environment:
      - NODE_ENV=production