version: '3.8'

# Minimal setup - just databases for development
services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: securechain_postgres
    environment:
      POSTGRES_DB: securechain
      POSTGRES_USER: securechain
      POSTGRES_PASSWORD: shivam2469
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - securechain_network

  # Neo4j Database
  neo4j:
    image: neo4j:5.15
    container_name: securechain_neo4j
    environment:
      NEO4J_AUTH: neo4j/neo4j_password
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - securechain_network

  # Redis for background tasks
  redis:
    image: redis:7-alpine
    container_name: securechain_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - securechain_network

volumes:
  postgres_data:
  neo4j_data:
  neo4j_logs:
  redis_data:

networks:
  securechain_network:
    driver: bridge